platform :ios, '8.0'
use_frameworks!

target 'pakr' do
  pod 'Typhoon', :head
  pod 'RealmSwift'
  pod 'AFNetworking'
  pod 'YStepperView'
  pod 'MBXPageViewController'
  pod 'Material', '~> 1.0'
  pod 'BEMCheckBox'
end

