platform :ios, '8.0'
use_frameworks!

target 'pakr' do
    pod 'FBSDKLoginKit'
    pod 'Google/SignIn'
    pod 'Parse'
    pod 'AFNetworking'
    pod 'AFNetworking'
    pod 'AYStepperView'
    pod 'MBXPageViewController'
    pod 'Material', '~> 1.0'
    pod 'BEMCheckBox'
end

