platform :ios, '8.0'
use_frameworks!

target 'pakr' do
    pod 'FBSDKLoginKit'
    pod 'Google/SignIn'
    pod 'AYStepperView'
    pod 'MBXPageViewController'
    pod 'Material', '~> 1.0'
    pod 'BEMCheckBox'
    pod 'AFNetworking'
    pod 'Alamofire', '~> 3.3'
    pod 'AYStepperView'
    pod 'MBXPageViewController'
    pod 'Material', '~> 1.0'
    pod 'BEMCheckBox'
    pod 'AWSCore'
    pod 'AWSS3'
    pod 'AWSCognito'
end

